<?php

namespace Database\Seeders;

use App\Models\Base\Country;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::newCountry('Albania');
        Country::newCountry('Algeria');
        Country::newCountry('Angola');
        Country::newCountry('Argentina');
        Country::newCountry('Armenia');
        Country::newCountry('Australia');
        Country::newCountry('Austria');
        Country::newCountry('Azerbaijan');
        Country::newCountry('Bahamas');
        Country::newCountry('Bahrain');
        Country::newCountry('Bangladesh');
        Country::newCountry('Belarus');
        Country::newCountry('Belgium');
        Country::newCountry('Benin');
        Country::newCountry('Bolivia');
        Country::newCountry('Bosnia and Herzegovina');
        Country::newCountry('Botswana');
        Country::newCountry('Brazil');
        Country::newCountry('Bulgaria');
        Country::newCountry('Burkina Faso');
        Country::newCountry('Cameroon');
        Country::newCountry('Cape Verde');
        Country::newCountry('Cayman Islands');
        Country::newCountry('Central African Republic');
        Country::newCountry('Chad');
        Country::newCountry('Chile');
        Country::newCountry('China');
        Country::newCountry('Colombia');
        Country::newCountry('Comoros');
        Country::newCountry('Congo');
        Country::newCountry('Costa Rica');
        Country::newCountry('Croatia');
        Country::newCountry('Cuba');
        Country::newCountry('Cyprus');
        Country::newCountry('Czech Republic');
        Country::newCountry('Democratic Republic of Congo');
        Country::newCountry('Denmark');
        Country::newCountry('Djibouti');
        Country::newCountry('Dominica');
        Country::newCountry('Ecudaor');
        Country::newCountry('Egypt');
        Country::newCountry('El Salvador');
        Country::newCountry('Equatorial Guinea');
        Country::newCountry('Eritrea');
        Country::newCountry('Estonia');
        Country::newCountry('Ethiopia');
        Country::newCountry('Finland');
        Country::newCountry('France');
        Country::newCountry('Gabon');
        Country::newCountry('Gambia');
        Country::newCountry('Georgia');
        Country::newCountry('Germany');
        Country::newCountry('Ghana');
        Country::newCountry('Greece');
        Country::newCountry('Guinea');
        Country::newCountry('Guinea-Bissau');
        Country::newCountry('Haiti');
        Country::newCountry('Honduras');
        Country::newCountry('Hong Kong');
        Country::newCountry('Hungary');
        Country::newCountry('Iceland');
        Country::newCountry('India');
        Country::newCountry('Indonesia');
        Country::newCountry('Iran');
        Country::newCountry('Iraq');
        Country::newCountry('Ireland');
        Country::newCountry('Israel');
        Country::newCountry('Italy');
        Country::newCountry('Ivory Coast');
        Country::newCountry('Jamaica');
        Country::newCountry('Japan');
        Country::newCountry('Jordan');
        Country::newCountry('Kenya');
        Country::newCountry('South Korea');
        Country::newCountry('North Korea');
        Country::newCountry('Kuwait');
        Country::newCountry('Latvia');
        Country::newCountry('Lebanon');
        Country::newCountry('Liberia');
        Country::newCountry('Libyan Arab Jamahiriya');
        Country::newCountry('Lithuania');
        Country::newCountry('Luxembourg');
        Country::newCountry('Macau');
        Country::newCountry('Macedonia');
        Country::newCountry('Madagascar');
        Country::newCountry('Malawi');
        Country::newCountry('Malaysia');
        Country::newCountry('Maldives');
        Country::newCountry('Mali');
        Country::newCountry('Malta');
        Country::newCountry('Mauritania');
        Country::newCountry('Mauritius');
        Country::newCountry('Mexico');
        Country::newCountry('Mongolia');
        Country::newCountry('Morocco');
        Country::newCountry('Mozambique');
        Country::newCountry('Netherlands');
        Country::newCountry('New Zealand');
        Country::newCountry('Niger');
        Country::newCountry('Nigeria');
        Country::newCountry('Norway');
        Country::newCountry('Oman');
        Country::newCountry('Pakistan');
        Country::newCountry('Papua New Guinea');
        Country::newCountry('Paraguay');
        Country::newCountry('Peru');
        Country::newCountry('Philippines');
        Country::newCountry('Poland');
        Country::newCountry('Portugal');
        Country::newCountry('Qatar');
        Country::newCountry('Republic of South Sudan');
        Country::newCountry('Romania');
        Country::newCountry('Russian Federation');
        Country::newCountry('Rwanda');
        Country::newCountry('San Marino');
        Country::newCountry('Saudi Arabia');
        Country::newCountry('Senegal');
        Country::newCountry('Serbia');
        Country::newCountry('Sierra Leone');
        Country::newCountry('Singapore');
        Country::newCountry('Slovakia');
        Country::newCountry('Slovenia');
        Country::newCountry('Somalia');
        Country::newCountry('South Africa');
        Country::newCountry('Spain');
        Country::newCountry('Sri Lanka');
        Country::newCountry('Sudan');
        Country::newCountry('Sweden');
        Country::newCountry('Switzerland');
        Country::newCountry('Syrian Arab Republic');
        Country::newCountry('Taiwan');
        Country::newCountry('Tanzania');
        Country::newCountry('Thailand');
        Country::newCountry('Trinidad and Tobago');
        Country::newCountry('Tunisia');
        Country::newCountry('Turkey');
        Country::newCountry('Uganda');
        Country::newCountry('Ukraine');
        Country::newCountry('United Arab Emirates');
        Country::newCountry('United Kingdom');
        Country::newCountry('Uruguay');
        Country::newCountry('Venezuela');
        Country::newCountry('Yemen');
        Country::newCountry('Zaire');
        Country::newCountry('Zambia');
        Country::newCountry('Zimbabwe');
        Country::newCountry('United States');
        Country::newCountry('Canada');
    }
}
